version: "3"

services:
    boltzd:
        container_name: boltzd
        hostname: boltzd
        image: massmux/boltzcli
        restart: on-failure
        volumes:
          - ${PWD}/.boltz-lnd:/root/.boltz-lnd
